$pdf_mode = 1;          # pdfLaTeX
$bibtex_use = 1;
@default_files = ('bao-cao.tex');
$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %O %S';
$clean_ext .= ' synctex.gz run.xml bbl bcf fdb_latexmk fls log out toc lof lot aux';
